import { LayoutResult } from '../layout/layoutEngine';
import { StickerShape } from '../state';

export interface SvgCutOptions {
  pageWidthMm: number;
  pageHeightMm: number;
  layout: LayoutResult;
  shape?: StickerShape;
  cornerRadiusMm?: number;
  registrationMarks?: boolean;
  /** Включать ли метки совмещения в файл контуров для плоттера (по умолчанию false, чтобы нож не резал мат) */
  includeMarksInSvg?: boolean;
  strokeColor?: string;
  strokeWidthMm?: number;
}

export interface RegistrationMarkPosition {
  cx: number;
  cy: number;
}

/**
 * Расчет координат 4 оптических меток совмещения по углам листа
 */
export function getRegistrationMarksPositions(pageWidthMm: number, pageHeightMm: number, offsetMm: number = 8): RegistrationMarkPosition[] {
  return [
    { cx: offsetMm, cy: offsetMm }, // Верх-Лево
    { cx: pageWidthMm - offsetMm, cy: offsetMm }, // Верх-Право
    { cx: offsetMm, cy: pageHeightMm - offsetMm }, // Низ-Лево
    { cx: pageWidthMm - offsetMm, cy: pageHeightMm - offsetMm }, // Низ-Право
  ];
}

/**
 * Программная генерация чистого векторного SVG в масштабе 1:1 для контурной плоттерной резки.
 * Полностью совместим с Easy Cut Studio, Silhouette Studio, CorelDraw, Illustrator.
 */
export function generateStickerCutSvg(options: SvgCutOptions): string {
  const {
    pageWidthMm,
    pageHeightMm,
    layout,
    shape = 'rect',
    cornerRadiusMm = 3,
    registrationMarks = false,
    includeMarksInSvg = false,
    strokeColor = '#ff0000',
    strokeWidthMm = 0.1,
  } = options;

  const svgLines: string[] = [];

  // 1. Корневой SVG с точными физическими размерами листа в миллиметрах
  svgLines.push(
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `width="${pageWidthMm}mm" height="${pageHeightMm}mm" ` +
    `viewBox="0 0 ${pageWidthMm} ${pageHeightMm}" ` +
    `version="1.1">`
  );

  // 2. Метаданные плоттерного файла
  svgLines.push(
    `  <!-- Generated by StickerFit - 1:1 Plotter Cut Contour -->`,
    `  <desc>StickerFit 1:1 Vector Cut Paths: ${layout.positions.length} items (${shape})</desc>`
  );

  // 3. Опорный габарит страницы для фиксации рабочей области листа в WYSIWYG режиме плоттерных программ
  svgLines.push(
    `  <!-- Page Boundary: фиксирует (0,0) и размер листа в Easy Cut Studio (WYSIWYG) -->`,
    `  <rect id="PageBoundary" x="0" y="0" width="${pageWidthMm}" height="${pageHeightMm}" fill="none" stroke="none" pointer-events="none" />`
  );

  // 4. Оптические метки совмещения плоттера (добавляются в SVG только при явном флаге includeMarksInSvg)
  if (registrationMarks && includeMarksInSvg) {
    const markPositions = getRegistrationMarksPositions(pageWidthMm, pageHeightMm, 8);
    const armLength = 4; // длина плеча креста (всего 8 мм)
    const targetRadius = 1.5;

    svgLines.push(`  <g id="RegistrationMarks" stroke="#000000" stroke-width="0.25" fill="none">`);
    for (const mark of markPositions) {
      const cx = mark.cx;
      const cy = mark.cy;
      // Горизонтальная линия креста
      svgLines.push(`    <line x1="${(cx - armLength).toFixed(3)}" y1="${cy.toFixed(3)}" x2="${(cx + armLength).toFixed(3)}" y2="${cy.toFixed(3)}" />`);
      // Вертикальная линия креста
      svgLines.push(`    <line x1="${cx.toFixed(3)}" y1="${(cy - armLength).toFixed(3)}" x2="${cx.toFixed(3)}" y2="${(cy + armLength).toFixed(3)}" />`);
      // Центральная окружность прицела
      svgLines.push(`    <circle cx="${cx.toFixed(3)}" cy="${cy.toFixed(3)}" r="${targetRadius.toFixed(3)}" />`);
    }
    // Маркер ориентации (квадрат в верхнем левом углу)
    const tl = markPositions[0];
    svgLines.push(`    <rect x="${(tl.cx - 1.5).toFixed(3)}" y="${(tl.cy - 1.5).toFixed(3)}" width="3" height="3" fill="#000000" stroke="none" />`);
    svgLines.push(`  </g>`);
  }

  // 5. Группа векторных контуров резки (CutContour)
  svgLines.push(
    `  <g id="CutContour" stroke="${strokeColor}" stroke-width="${strokeWidthMm}" fill="none">`
  );

  for (const pos of layout.positions) {
    const { xMm, yMm, widthMm, heightMm } = pos;

    if (shape === 'circle') {
      const d = Math.min(widthMm, heightMm);
      const r = d / 2;
      const cx = xMm + widthMm / 2;
      const cy = yMm + heightMm / 2;
      svgLines.push(
        `    <circle cx="${cx.toFixed(3)}" cy="${cy.toFixed(3)}" r="${r.toFixed(3)}" />`
      );
    } else if (shape === 'rounded') {
      const maxR = Math.min(widthMm, heightMm) / 2;
      const r = Math.max(0, Math.min(cornerRadiusMm, maxR));
      svgLines.push(
        `    <rect x="${xMm.toFixed(3)}" y="${yMm.toFixed(3)}" ` +
        `width="${widthMm.toFixed(3)}" height="${heightMm.toFixed(3)}" ` +
        `rx="${r.toFixed(3)}" ry="${r.toFixed(3)}" />`
      );
    } else {
      // Прямоугольник
      svgLines.push(
        `    <rect x="${xMm.toFixed(3)}" y="${yMm.toFixed(3)}" ` +
        `width="${widthMm.toFixed(3)}" height="${heightMm.toFixed(3)}" />`
      );
    }
  }

  svgLines.push(`  </g>`);
  svgLines.push(`</svg>`);

  return svgLines.join('\n');
}

/**
 * Генерация отдельного файла шаблона реперов (для вычерчивания плоттерной ручкой на прозрачной пленке)
 */
export function generateRegistrationTemplateSvg(pageWidthMm: number, pageHeightMm: number, offsetMm: number = 8): string {
  const markPositions = getRegistrationMarksPositions(pageWidthMm, pageHeightMm, offsetMm);
  const armLength = 4;
  const targetRadius = 1.5;

  const lines: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<svg xmlns="http://www.w3.org/2000/svg" width="${pageWidthMm}mm" height="${pageHeightMm}mm" viewBox="0 0 ${pageWidthMm} ${pageHeightMm}" version="1.1">`,
    `  <!-- StickerFit Registration Template for Calibration Overlay -->`,
    `  <rect id="PageBoundary" x="0" y="0" width="${pageWidthMm}" height="${pageHeightMm}" fill="none" stroke="#000000" stroke-width="0.1" stroke-dasharray="2,2" />`,
    `  <g id="RegistrationMarks" stroke="#000000" stroke-width="0.25" fill="none">`,
  ];

  for (const mark of markPositions) {
    lines.push(
      `    <line x1="${(mark.cx - armLength).toFixed(3)}" y1="${mark.cy.toFixed(3)}" x2="${(mark.cx + armLength).toFixed(3)}" y2="${mark.cy.toFixed(3)}" />`,
      `    <line x1="${mark.cx.toFixed(3)}" y1="${(mark.cy - armLength).toFixed(3)}" x2="${mark.cx.toFixed(3)}" y2="${(mark.cy + armLength).toFixed(3)}" />`,
      `    <circle cx="${mark.cx.toFixed(3)}" cy="${mark.cy.toFixed(3)}" r="${targetRadius.toFixed(3)}" />`
    );
  }

  const tl = markPositions[0];
  lines.push(
    `    <rect x="${(tl.cx - 1.5).toFixed(3)}" y="${(tl.cy - 1.5).toFixed(3)}" width="3" height="3" fill="#000000" stroke="none" />`,
    `  </g>`,
    `</svg>`
  );

  return lines.join('\n');
}

/**
 * Скачивание векторного SVG в браузере
 */
export function downloadCutSvgBlob(svgContent: string, fileName: string = 'stickers-cut-contour.svg'): void {
  const blob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}
